### ISSUE TITLE
Ambiguous species

### ISSUE THREAD

**Issue by indigotran** [DataDrivenEcologicalSynthesis/VirtualBiogeography#33]
Suggestion for class: Are there any ambiguous fish species in the movie? Or are we able to identify them all to the species level?

**Comment by phylojenie** [comment]
I have not looked at many of the screenshots yet but I do know of one problematic species already: Nigel the pelican is a Brown Pelican (_Pelecanus occidentalis_) according to some sources and an Australian Pelican (_Pelecanus conspicillatus_) according to others. He looks most like a Brown Pelican, but brown pelicans don't occur in Australia. So he's either an ambiguous species that doesn't exist, or a real species that is in the wrong location.

**Comment by Crataegus9** [comment]
Also there are many fishes that are really blurry in the screenshots. Also, Chaetodon collare is the species that ressemble the most the butterflyfish that is seen on the screenshot SS_00-01-30_GBR, but with a lot of ambiguity. Otherwise, the color patterns don't fit any species of Chaetodontidae recorded in Australia.

**Comment by indigotran** [comment]
Some parts of the movie have multiple species moving at a very fast pace and the frame per second is very high, so I couldn't get a very clear screenshot. I couldn't make a gif of cut the video out of the movie so I'm not sure how to include this. 
I found a couple of videos you can watch here, but the quality is not that good either: [Opening Scene](https://youtu.be/HG3L98NFyro) and [Great Barrier Reef / Way to School](https://youtu.be/6cP8ADcgN8U). I hope this helps as I cannot record anything while on DisneyPlus.

**Comment by phylojenie** [comment]
No worries Indigo, you've put in a lot of work to grabbing the screenshots as-is! I have subscribed to a free trial of Disney+ and I'm going to try and watch through my section of the timestamps to see if it's a little easier to identify stuff.

**Comment by indigotran** [comment]
@phylojenie You're doing great work! @superornitho If anyone needs a link to the *hush hush* site to watch the movie, I can send it to you as well.

**Comment by Crataegus9** [comment]
Most of the scenes at the beginning of the movie are found on youtube, I played the video at 0,25x normal speed to better see some details.

**Comment by phylojenie** [comment]
This also raises the question: what happens if we find a fish that isn't on our pre-assembled list? Do we try to track down what that fish might be, or do we ignore it and move on? 

Personally I am for ignoring any fishes that aren't readily identifiable from the species list and photos we already have; mostly because if the movie does include ambiguous/made up animals then we might waste a lot of time tracking down an animal that doesn't exist.

**Comment by indigotran** [comment]
Yes let's move on for now and focus on what you can identify. For the ones you have trouble with, make a note / flag the image that contains that species and save it for later.

**Comment by Crataegus9** [comment]
Yep, many fishes won’t be readily identifiable and I think ignoring these will make our lives considerably easier. It also took me a while to identify every fish in the first reef scene and some (2 or 3) were not in the fan-created list. If we want to save some time we could just stick to the preexisting list.

**Comment by aliczner** [comment]
> This also raises the question: what happens if we find a fish that isn't on our pre-assembled list? Do we try to track down what that fish might be, or do we ignore it and move on?
> 
> Personally I am for ignoring any fishes that aren't readily identifiable from the species list and photos we already have; mostly because if the movie does include ambiguous/made up animals then we might waste a lot of time tracking down an animal that doesn't exist.

I think this is what the "issue" raised by the classmate is getting at specifically. So I think our response to this given the comments is to note the number of ambiguous or "unknown fish". Maybe we can add "unknown" as a row in the species list data to keep track? Our justification could be just we could not identify these species. Having the justification be "it wasn't on the list we pulled from the internet" doesn't sound very scientific :P

**Comment by phylojenie** [comment]
I have added a "contains unidentifiable species" to the screenshot analysis spreadsheet. This way if we can't ID something easily we can flag it, then if we have time we can go back and try to find a positive ID.

Under normal circumstances skipping an ID because it's not on the list isn't ideal, but we're also doing this project under severe time contraints so I think they'll forgive us for not perfectly IDing every species in the movie 😅
